Update android.yml

diff --git a/.github/workflows/android.yml b/.github/workflows/android.yml
--- a/.github/workflows/android.yml
+++ b/.github/workflows/android.yml
@@ -21,7 +21,7 @@ jobs:
     if: github.event.inputs.action == 'build' || github.event_name != 'workflow_dispatch'
     runs-on: ubuntu-latest
     env:
-      RELEASE_STORE_FILE: keystore.jks
+      RELEASE_STORE_FILE: ../keystore.jks
       RELEASE_STORE_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}
       RELEASE_KEY_ALIAS: ${{ secrets.KEY_ALIAS }}
       RELEASE_KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}
@@ -41,9 +41,16 @@ jobs:
           platform-version: "34"
       - name: Grant execute permission for gradlew
         run: chmod +x gradlew
+      - name: Check keystore exists
+        run: |
+          if [ ! -f "../keystore.jks" ]; then
+            echo "Error: ../keystore.jks not found!"
+            exit 1
+          fi
+          echo "Keystore file exists"
       - name: Create gradle.properties
         run: |
-          echo "RELEASE_STORE_FILE=keystore.jks" >> app/gradle.properties
+          echo "RELEASE_STORE_FILE=../keystore.jks" >> app/gradle.properties
           echo "RELEASE_STORE_PASSWORD=${{ secrets.KEYSTORE_PASSWORD }}" >> app/gradle.properties
           echo "RELEASE_KEY_ALIAS=${{ secrets.KEY_ALIAS }}" >> app/gradle.properties
           echo "RELEASE_KEY_PASSWORD=${{ secrets.KEY_PASSWORD }}" >> app/gradle.properties
@@ -169,7 +176,7 @@ jobs:
           echo "Zipaligning APK..."
           $ANDROID_HOME/build-tools/34.0.0/zipalign -v 4 app/build/outputs/apk/release/app-release-unsigned.apk app/build/outputs/apk/release/app-release-aligned.apk
           echo "Signing APK..."
-          $ANDROID_HOME/build-tools/34.0.0/apksigner sign --ks keystore.jks --ks-pass pass:${{ secrets.KEYSTORE_PASSWORD }} --ks-key-alias ${{ secrets.KEY_ALIAS }} --key-pass pass:${{ secrets.KEY_PASSWORD }} app/build/outputs/apk/release/app-release-aligned.apk
+          $ANDROID_HOME/build-tools/34.0.0/apksigner sign --ks ../keystore.jks --ks-pass pass:${{ secrets.KEYSTORE_PASSWORD }} --ks-key-alias ${{ secrets.KEY_ALIAS }} --key-pass pass:${{ secrets.KEY_PASSWORD }} app/build/outputs/apk/release/app-release-aligned.apk
           echo "Moving final APK..."
           mv app/build/outputs/apk/release/app-release-aligned.apk app/build/outputs/apk/release/app-release.apk
       - name: Upload APK
